#ifndef COMMON_CORE_H
#define COMMON_CORE_H

#include <logging/logger.h>

#define UNUSED(x) ((void)(x))

typedef enum {
	
	SHATTER_SUCCESS = 0,
	
	SHATTER_RENDERER_INIT_FAILURE,
	SHATTER_RENDERER_LOOP_ERROR,
	SHATTER_RENDERER_CLEANUP_FAILURE,
	
	SHATTER_GLFW_INIT_FAILURE,
	SHATTER_GLFW_TERMINATE_FAILURE,
	SHATTER_GLFW_WINDOW_FAILURE,
	
	SHATTER_SURFACE_INIT_FAILURE,
	
	SHATTER_VULKAN_DEBUG_SETUP_FAILURE,
	SHATTER_VULKAN_INSTANCE_FAILURE,
	SHATTER_VULKAN_LAYER_FAILURE,
	SHATTER_VULKAN_PHYSICAL_DEVICE_CHOICE_FAILURE,
	SHATTER_VULKAN_LOGICAL_DEVICE_INIT_FAILURE,
	SHATTER_VULKAN_SWAP_CHAIN_INIT_FAILURE,
	SHATTER_VULKAN_IMAGE_VIEW_INIT_FAILURE,
	SHATTER_VULKAN_GRAPHICS_PIPELINE_INIT_FAILURE,
	SHATTER_VULKAN_SHADER_MODULE_INIT_FAILURE,
	SHATTER_VULKAN_RENDER_PASS_INIT_FAILURE,
	SHATTER_VULKAN_PIPELINE_LAYOUT_INIT_FAILURE,
	SHATTER_VULKAN_FRAME_BUFFER_INIT_FAILURE,
	SHATTER_VULKAN_COMMAND_POOL_INIT_FAILURE,
	SHATTER_VULKAN_COMMAND_BUFFER_INIT_FAILURE,
	SHATTER_VULKAN_COMMAND_BUFFER_RECORD_FAILURE,
	SHATTER_VULKAN_SYNC_OBJECT_INIT_FAILURE,
	SHATTER_VULKAN_SEMAPHORE_INIT_FAILURE,
	SHATTER_VULKAN_FENCE_INIT_FAILURE,
	SHATTER_VULKAN_DRAW_FRAME_FAILURE,
	
} shatter_status_t;

#endif // COMMON_CORE_H

