#ifndef COMMON_CORE_H
#define COMMON_CORE_H

#include <logger.h>

#define UNUSED(x) ((void)(x))

#define MAX_FILEPATH_LEN 255
#define MAX_TITLE_LENGTH 255

typedef enum {
	
	SHATTER_SUCCESS = 0,
	
	SHATTER_DYNAMIC_LIBRARY_INVALID_API_INDEX,
	SHATTER_DYNAMIC_LIBRARY_LOAD_FAILURE,
	SHATTER_DYNAMIC_LIBRARY_LOAD_VTABLE_FAILURE,
	SHATTER_DYNAMIC_LIBRARY_UNLOAD_FAILURE,
	SHATTER_DYNAMIC_LIBRARY_RELOAD_RECOVERED,
	SHATTER_DYNAMIC_LIBRARY_RELOAD_FAILURE,
	
	SHATTER_RENDERER_INIT_FAILURE,
	SHATTER_RENDERER_LOOP_FAILURE,
	SHATTER_RENDERER_CLEANUP_NONE,
	SHATTER_RENDERER_CLEANUP_FAILURE,
	SHATTER_RENDERER_RELOAD_FAILURE,
	SHATTER_RENDERER_RUN_FAILURE,
	
	SHATTER_GLFW_INIT_FAILURE,
	SHATTER_GLFW_TERMINATE_FAILURE,
	SHATTER_GLFW_WINDOW_FAILURE,
	
	SHATTER_SURFACE_INIT_FAILURE,
	
	SHATTER_VULKAN_DEBUG_SETUP_FAILURE,
	
	SHATTER_VULKAN_INSTANCE_FAILURE,
	
	SHATTER_VULKAN_LAYER_FAILURE,
	
	SHATTER_VULKAN_PHYSICAL_DEVICE_CHOICE_FAILURE,
	SHATTER_VULKAN_PHYSICAL_DEVICE_GET_MEMORY_TYPE_FAILURE,
	
	SHATTER_VULKAN_LOGICAL_DEVICE_INIT_FAILURE,
	
	SHATTER_VULKAN_SWAP_CHAIN_INIT_FAILURE,
	SHATTER_VULKAN_SWAP_CHAIN_RECREATION,
	SHATTER_VULKAN_SWAP_CHAIN_RECREATION_FAILURE,
	SHATTER_VULKAN_SWAP_CHAIN_ACQUISITION_FAILURE,
	
	SHATTER_VULKAN_GRAPHICS_QUEUE_SUBMITION_FAILURE,
	SHATTER_VULKAN_PRESENT_QUEUE_SUBMITION_FAILURE,
	
	SHATTER_VULKAN_IMAGE_VIEW_INIT_FAILURE,
	
	SHATTER_VULKAN_GRAPHICS_PIPELINE_INIT_FAILURE,
	
	SHATTER_VULKAN_SHADER_READ_FAILURE,
	SHATTER_VULKAN_SHADER_MODULE_INIT_FAILURE,
	
	SHATTER_VULKAN_RENDER_PASS_INIT_FAILURE,
	
	SHATTER_VULKAN_PIPELINE_LAYOUT_INIT_FAILURE,
	
	SHATTER_VULKAN_FRAME_BUFFER_INIT_FAILURE,
	
	SHATTER_VULKAN_COMMAND_POOL_INIT_FAILURE,
	
	SHATTER_VULKAN_VERTEX_BUFFER_INIT_FAILURE,
	SHATTER_VULKAN_VERTEX_BUFFER_ALLOCATE_FAILURE,
	
	SHATTER_VULKAN_COMMAND_BUFFER_INIT_FAILURE,
	SHATTER_VULKAN_COMMAND_BUFFER_RECORD_FAILURE,
	
	SHATTER_VULKAN_SYNC_OBJECT_INIT_FAILURE,
	SHATTER_VULKAN_SEMAPHORE_INIT_FAILURE,
	SHATTER_VULKAN_FENCE_INIT_FAILURE,
	
	SHATTER_VULKAN_DRAW_FRAME_FAILURE,
	
	SHATTER_OPENGL_GLAD_INIT_FAILURE,
	SHATTER_OPENGL_RENDERER_INIT_FAILURE,
	
} shatter_status_t;

static const char *vulkan_api_library_filepath = "api_libraries/vulkan_api.so";
static const char *opengl_api_library_filepath = "api_libraries/opengl_api.so";

#endif // COMMON_CORE_H

