#ifndef COMMON_CORE_H
#define COMMON_CORE_H

#include <logging/logger.h>

typedef enum {
	
	SHATTER_SUCCESS = 0,
	
	SHATTER_RENDERER_INIT_FAILURE,
	SHATTER_RENDERER_LOOP_ERROR,
	SHATTER_RENDERER_CLEANUP_FAILURE,
	
	SHATTER_GLFW_INIT_FAILURE,
	SHATTER_GLFW_TERMINATE_FAILURE,
	SHATTER_GLFW_WINDOW_FAILURE,
	
	SHATTER_SURFACE_INIT_FAILURE,
	
	SHATTER_VULKAN_DEBUT_SETUP_FAILURE,
	
	SHATTER_VULKAN_INSTANCE_FAILURE,
	SHATTER_VULKAN_LAYER_FAILURE,
	SHATTER_VULKAN_PHYSICAL_DEVICE_CHOICE_FAILURE,
	SHATTER_VULKAN_LOGICAL_DEVICE_INIT_FAILURE,
} shatter_status_t;

#endif // COMMON_CORE_H

